apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          serviceAnnotations:
            cloud.google.com/app-protocols: '{"https":"HTTPS","http2":"HTTP"}'
            cloud.google.com/backend-config: '{"default": "cloudarmor"}'
            cloud.google.com/neg: '{"ingress": true}'
  meshConfig:
    serviceSettings:
      - settings:
          clusterLocal: true
        hosts:
          - "*.argocd.svc.cluster.local"
