apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - virtualservice.yaml
  - external-secrets.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - app-projects.yaml
  - namespace.yaml
