#!/usr/bin/env groovy

def gv

pipeline {
    agent any
    tools {
        maven 'Maven 3.8'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "jenkins/java-maven-app/Jenkinsfile-simple-pipeline/script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    gv.buildJar()
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    gv.buildImage()
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}
