version: '3'
services:
  java-app:
    image: us.gcr.io/sws-globalsre-cug01-qa/java-mysql-docker:1.0
    ports:
      - 8080:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=team-member-projects
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
    volumes:
      - mysql-data:/var/lib/mysql
  phpadmin:
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOST=mysql
volumes:
  mysql-data:
    driver: local
