- op: replace
  path: /spec/data
  value:
    - secretKey: server.secretkey
      remoteRef:
        key: argocd-server-key
    - secretKey: github.clientId
      remoteRef:
        key: argocd-gke-3-github-client-id
    - secretKey: github.clientSecret
      remoteRef:
        key: argocd-gke-3-github-client-secret
    - secretKey: github.username
      remoteRef:
        key: github-jenkins-username
    - secretKey: github.token
      remoteRef:
        key: github-jenkins-token
    - secretKey: github.ncr.tech.username
      remoteRef:
        key: ncr-tech-content-dev-github-user
    - secretKey: github.ncr.tech.token
      remoteRef:
        key: ncr-tech-content-dev-github-token
    - secretKey: webhook.github.secret
      remoteRef:
        key: github-argocd-webhook

- op: replace
  path: /spec/target
  value:
    name: argocd-secret
    creationPolicy: Owner
