- op: replace
  path: /spec/data
  value:
    - secretKey: github.clientId
      remoteRef:
        key: argocd-github-client-id
    - secretKey: github.clientSecret
      remoteRef:
        key: argocd-github-client-secret
    - secretKey: github.username
      remoteRef:
        key: argocd-github-username
    - secretKey: github.token
      remoteRef:
        key: argocd-github-token
    - secretKey: webhook.github.secret
      remoteRef:
        key: github-argocd-webhook

- op: replace
  path: /spec/target
  value:
    name: argocd-secret
    creationPolicy: Owner
