apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../ArgoCD/base
namespace: argocd
patches:
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: VirtualService
      name: argocd-server
    path: virtual-service-patch.yaml
  - target:
      version: v1beta1
      kind: ExternalSecret
      name: argocd-secret
      namespace: argocd
    path: external-secrets-patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-patch.yaml
