- op: replace
  path: /spec
  value:
    gateways:
      - istio-system/ingressgateway
    hosts:
      - "argocd-test.gsre.ncr.com"
    http:
      - route:
          - destination:
              host: argocd-server
              port:
                number: 80
