# Edit and fill n the value of <GCP_Project>, <region>, <GCP_Project>
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gsre-gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: <GCP_Project>
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: <region>
          # name of the GKE cluster
          clusterName: <cluster_name>
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: <GCP_Project>
          # reference the sa from above
          serviceAccountRef:
            name: kube-external-secrets
            namespace: external-secrets
